spring:
  profiles:
    default: local

  datasource:
    url: jdbc:h2:tcp://localhost/~/taskListApplication
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update

management:
  endpoint:
    beans:
      cache:
        time-to-live: "10s"
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "health,env"
---
spring:
  config:
    activate:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true # (2.5~) Hibernate 초기화 이후 data.sql 실행

  h2:
    console:
      enabled: true

---
spring:
  config:
    activate:
      on-profile: test

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never # SQL Initializer 사용 안하겟다는 명시